spring:
  application:
    name: TheraFlow


  jpa:
    hibernate:
      ddl-auto: validate

  jackson:
    default-property-inclusion: non_null

  mail:
    host: smtp.gmail.com
    port: 587
    username: i1voloshyn.ph@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp

  flyway:
    enabled: true
    locations: "classpath:db/migration"

theraflow:
  password-length:
    min-length: 10
    max-length: 64

app:
  base-url: http://localhost:8080
  mail-from: ${MAIL_FROM}

  security:
    jwt:
      access:
        secret: ${JWT_ACCESS_SECRET}
        expiration: 10m # 10 minute
      refresh:
        expiration: 30d  # 30 days

      email:
        secret: ${JWT_EMAIL_SECRET}
        expiration: 60 # 60 minutes

    password:
      reset:
        expiration: 30m

