spring:
  application:
    name: TheraFlow

  jpa:
    hibernate:
      ddl-auto: validate

  jackson:
    default-property-inclusion: non_null

  flyway:
    enabled: true
    locations: "classpath:db/migration"

theraflow:
  password-length:
    min-length: 10
    max-length: 64
